main/urls.py
from django.urls import path
from main.views import main, register, login_user, logout_user, get_books_json_preview

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-preview-books/', get_books_json_preview, name="get_books_json_preview")

]

tales_tails_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('mybooks/', include('mybooks.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

user_profile/urls.py
from django.urls import path
from user_profile.views import user_profile, get_user_json, edit_profile, show_user_json, edit_profile_flutter, edit_profile_flutter_user


app_name = 'user_profile'

urlpatterns = [
    path('', user_profile, name='user_profile'),
    path('get-user/', get_user_json, name='get_user_json'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('show-user/', show_user_json, name='show_user_json'),
    path('edit-profile-admin/', edit_profile_flutter, name='edit_profile'),
    path('edit-profile-user/', edit_profile_flutter_user, name='edit_profile_flutter_user'),
]

user_profile/models.py
from django.db import models

# Create your models here.

user_profile/views.py
from django.shortcuts import render
from main.models import Book, User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers

@login_required(login_url='/login')
def user_profile(request):
    user = request.user
    if user.user_type == 'ADMIN':
        all_borrowed_books = Book.objects.filter(is_borrowed = True).values()
        all_member_user = User.objects.filter(user_type = 'MEMBER')
        context = {
            'user': user,
            'member_users': all_member_user,
            'books': all_borrowed_books,
        }
        return render(request, 'admin_profile.html', context)
    
    books = Book.objects.filter(borrower = user)
    context = {
        'user': user,
        'books': books,
    }
    
    return render(request, 'member_profile.html', context)

def get_user_json(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            user = request.user
            user_data = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'username': user.username,
                'email': user.email,
                'date_of_birth': user.date_of_birth,
                'user_type' : user.user_type,
            }
            return JsonResponse(user_data)
        else:
            return JsonResponse({'message': 'User is not authenticated'})

def edit_profile(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get("first_name")
        user.last_name = request.POST.get("last_name")
        user.username = request.POST.get("username")
        user.date_of_birth = request.POST.get("date_of_birth")
        user.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def show_user_json(request):
    data = User.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
import json
from django.shortcuts import render
from main.models import Book, User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def user_profile(request):
    user = request.user
    if user.user_type == 'ADMIN':
        all_borrowed_books = Book.objects.filter(is_borrowed = True).values()
        all_member_user = User.objects.filter(user_type = 'MEMBER')
        context = {
            'user': user,
            'member_users': all_member_user,
            'books': all_borrowed_books,
        }
        return render(request, 'admin_profile.html', context)
    
    books = Book.objects.filter(borrower = user)
    context = {
        'user': user,
        'books': books,
    }
    
    return render(request, 'member_profile.html', context)

def get_user_json(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            user = request.user
            user_data = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'username': user.username,
                'email': user.email,
                'date_of_birth': user.date_of_birth,
                'user_type' : user.user_type,
            }
            return JsonResponse(user_data)
        else:
            return JsonResponse({'user_type': 'Not authenticated'})

def edit_profile(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get("first_name")
        user.last_name = request.POST.get("last_name")
        # user.username = request.POST.get("username")
        # user.date_of_birth = request.POST.get("date_of_birth")
        user.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt 
def edit_profile_flutter(request):
    if request.method == 'POST':
    
        data = json.loads(request.body)
        first_name = data.get('first_name')
        last_name = data.get('last_name')

        user = request.user
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        return JsonResponse({"status": "success"}, status=200)

    return HttpResponseNotFound()

@csrf_exempt 
def edit_profile_flutter_user(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        new_username = data.get('username')
        
        # Memeriksa apakah username sudah ada dalam basis data
        existing_user = User.objects.filter(username=new_username).exists()

        if existing_user:
            # Username sudah ada, kirim respons bahwa username sudah digunakan
            return JsonResponse({"status": "error", "message": "Username sudah digunakan"}, status=400)

        # Username belum ada, lanjutkan untuk menyimpan perubahan
        user = request.user
        user.username = new_username
        user.save()

        return JsonResponse({"status": "success"}, status=200)

    return HttpResponseNotFound()

user_profile/templates/admin_profile.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<div class="mx-20 my-10 rounded-xl border-4" style="background-color: #FEFADD; border-color: #724E2B;">
    <h1 class="w-full text-center rounded-lg lg border-b-4 py-6 text-4xl" style="font-family: 'Darumadrop One'; color: #FEFADD; background-color: #C85A35; border-color: #724E2B;">
        Admin Profile
    </h1>
    <div class="flex justify-center my-10">
        <div class="border-4 rounded w-25 h-25 px-20" style="background-color: #DBBC7F; border-color: #724E2B; color: #DBBC7F;">
            .
        </div>
        <div class="ml-10" style="font-family: 'Mochiy Pop P One';" id="user-data">
        </div>
    </div>
    <div class="flex justify-center my-10" style="font-family: 'Mochiy Pop P One'; color: #724E2B;">
        <a id="openModal" class="border-2 rounded mx-5 p-2" style="border-color: #724E2B;" href="#">Edit Profile</a>
    </div>
</div>

<!-- <div class="flex justify-center">
    <h1 class="p-5 text-4xl border-4 rounded-xl" style="background-color: #DBBC7F; color: #FEFADD; -webkit-text-stroke: 2px #724E2B; font-family: 'Darumadrop One'; border-color: #724E2B;">List of Members</h1>
</div>

{% for member_user in member_users %}
<div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center bg-orange-100 border-4 border-yellow-900">
        
    <div class=" px-20 pt-4">
        <img alt="no image">
    </div>
    <div>
        <div class= "data pr-1 pt-2 tag">
            <h1 class="truncate">{{ member_user.username }}</h1>
        
        </div>
        <p class=" data pt-3 text-sm pb-2">Stock: <span class="ml-2">1</span></p>
    
        <div class="w-full pb-2">
            <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" id="{{member_user.id}}" onclick="openModalUser(this.id)">
                Details
            </button>
        </div>
    </div>
</div> -->

<!-- START Modal user detail -->
<!-- <div id="ModalUser{{member_user.id}}" class="modal fixed hidden inset-0 z-50 overflow-auto bg-black bg-opacity-50 flex items-center justify-center">
    <div class="modal-content bg-white p-4 rounded max-w-md mx-auto"> -->
        <!-- Modal Header -->
        <!-- <div class="modal-header mb-4">
            <span id="{{member_user.id}}" class="modal-close cursor-pointer text-2xl" onclick="closeModalUser(this.id)">&times;</span>
            <h2 class="text-lg font-bold">Modal Title</h2>
        </div> -->
        <!-- Modal Body -->
        <!-- <div class="modal-body">
            <p>{{ member_user.first_name }} {{ member_user.last_name }}</p>
            <p>{{ member_user.username }}</p>
            <p>{{ member_user.date_of_birth }}</p>
            <p>{{ member_user.email }}</p>
            
        </div>
    </div>
</div> -->
<!-- END Modal User Detail -->
<!-- 
{% endfor %} -->


<!-- START Modal Edit Profile -->
<div id="myModal" class="modal fixed hidden inset-0 z-50 overflow-auto bg-black bg-opacity-50 flex items-center justify-center">
    <div class="modal-content bg-white p-4 rounded max-w-md mx-auto">
        <!-- Modal Header -->
        <div class="modal-header mb-4">
            <span id="closeModal" class="modal-close cursor-pointer text-2xl">&times;</span>
            <h2 class="text-lg font-bold">Modal Title</h2>
        </div>
        <!-- Modal Body -->
        <div class="modal-body">
            <form id="form" onsubmit="return false;">
                
            </form>
            <button type="button" id="button_save">Save Changes</button>
        </div>
    </div>
</div>
<!-- END Modal Edit Profile -->

<script>
async function getUserData() {
    return fetch("{% url 'user_profile:get_user_json' %}").then((res) => res.json())
}

async function refreshUserData() {
    document.getElementById("user-data").innerHTML = ""
    document.getElementById("form").innerHTML = ""
    const user = await getUserData()
    let htmlStringUserData = `
        <div class="mb-5">
                <p class="text-sm">Name</p>
                <p class="text-xl">${ user.first_name } ${ user.last_name }</p>
            </div>

            <div class="my-5">
                <p class="text-sm">Username</p>
                <p class="text-xl">${ user.username }</p>
            </div>
            
            <div class="my-5">
                <p class="text-sm">Date of Birth</p>
                <p class="text-xl">${ user.date_of_birth }</p>  
            </div>

            <div class="mt-5">
                <p class="text-sm">E-mail</p>
                <p class="text-xl">${ user.email }</p>
            </div>
        </div>
    `
    document.getElementById("user-data").innerHTML = htmlStringUserData

    let htmlStringModalForm = `
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="col-form-label">Username:</label>
                    <input type="text" class="form-control" id="username" name="username"></input>
                </div>
    `
    document.getElementById("form").innerHTML = htmlStringModalForm
}

refreshUserData()

function editProfile() {
        fetch("{% url 'user_profile:edit_profile' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshUserData)

        document.getElementById("form").reset()
        document.getElementById('myModal').classList.add('hidden');
        return false
    }

document.getElementById("button_save").onclick = editProfile

document.getElementById('openModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.remove('hidden');
});

document.getElementById('closeModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.add('hidden');
});


function openModalUser(Id) {
    document.getElementById('ModalUser' + Id).classList.remove('hidden');
    }

function closeModalUser(Id) {
    document.getElementById('ModalUser' + Id).classList.add('hidden');
    }

</script>

{% endblock %}

user_profile/templates/member_profile.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<div class="mx-20 my-10 rounded-xl border-4" style="background-color: #FEFADD; border-color: #724E2B;">
    <h1 class="w-full text-center rounded-lg lg border-b-4 py-6 text-4xl" style="font-family: 'Darumadrop One'; color: #FEFADD; background-color: #89C8C5; border-color: #724E2B;">
        Profile
    </h1>
    <div class="flex justify-center my-10">
        <div class="border-4 rounded w-25 h-25 px-20" style="background-color: #DBBC7F; border-color: #724E2B; color: #DBBC7F;">
            .
        </div>
        <div class="ml-10" style="font-family: 'Mochiy Pop P One';" id="user-data">
        </div>
    </div>
    <div class="flex justify-center my-10" style="font-family: 'Mochiy Pop P One'; color: #724E2B;">
        <a id="openModal" class="border-2 rounded mx-5 p-2" style="border-color: #724E2B;" href="#">Edit Profile</a>
    </div>
</div>

{% for book in books %}
<p>{{ book.title }}</p>
{% endfor %}

<!-- Modal Edit Profile -->
<div id="myModal" class="modal fixed hidden inset-0 z-50 overflow-auto bg-black bg-opacity-50 flex items-center justify-center">
    <div class="modal-content bg-white p-4 rounded max-w-md mx-auto">
        <!-- Modal Header -->
        <div class="modal-header mb-4">
            <span id="closeModal" class="modal-close cursor-pointer text-2xl">&times;</span>
            <h2 class="text-lg font-bold">Modal Title</h2>
        </div>
        <!-- Modal Body -->
        <div class="modal-body">
            <form id="form" onsubmit="return false;">
                
            </form>
            <button type="button" id="button_save">Save Changes</button>
        </div>
    </div>
</div>

<script>
async function getUserData() {
        return fetch("{% url 'user_profile:get_user_json' %}").then((res) => res.json())
    }

async function refreshUserData() {
    document.getElementById("user-data").innerHTML = ""
    document.getElementById("form").innerHTML = ""
    const user = await getUserData()
    let htmlStringUserData = `
        <div class="mb-5">
                <p class="text-sm">Name</p>
                <p class="text-xl">${ user.first_name } ${ user.last_name }</p>
            </div>

            <div class="my-5">
                <p class="text-sm">Username</p>
                <p class="text-xl">${ user.username }</p>
            </div>
            
            <div class="my-5">
                <p class="text-sm">Date of Birth</p>
                <p class="text-xl">${ user.date_of_birth }</p>  
            </div>

            <div class="mt-5">
                <p class="text-sm">E-mail</p>
                <p class="text-xl">${ user.email }</p>
            </div>
        </div>
    `
    document.getElementById("user-data").innerHTML = htmlStringUserData

    let htmlStringModalForm = `
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="col-form-label">Username:</label>
                    <input type="text" class="form-control" id="username" name="username"></input>
                </div>
    
    `
    document.getElementById("form").innerHTML = htmlStringModalForm
}

// h
refreshUserData()

function editProfile() {
        fetch("{% url 'user_profile:edit_profile' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshUserData)

        document.getElementById("form").reset()
        document.getElementById('myModal').classList.add('hidden');
        return false
    }

document.getElementById("button_save").onclick = editProfile

document.getElementById('openModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.remove('hidden');
});

document.getElementById('closeModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.add('hidden');
});

</script>

{% endblock %}