catalog/urls.py
from django.urls import path
from catalog.views import catalog, search_books, get_books_json, search_book, book_borrowed, delete_book, add_book, book_borrowed_flutter, add_book_flutter, delete_book_flutter
from user_profile.views import get_user_json

app_name = 'catalog'

urlpatterns = [
    path('', catalog, name='catalog'),
    path("search/<str:query>", search_books, name='search'),
    path("get-books/", get_books_json, name='get_books_json'),
    path("search-book/", search_book, name='search_book'),
    path("borrow-book/<int:id>", book_borrowed, name='borrow_book'),
    path("delete-book/<int:id>", delete_book, name='delete_book'),
    path('get-user/', get_user_json, name='get_user_json'),
    path('add-book/', add_book, name='add_book'),
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
    path('book-borrowed-flutter/<int:id>', book_borrowed_flutter, name='borrow_book_flutter')
]

main/urls.py
from django.urls import path
from main.views import main, register, login_user, logout_user, get_books_json_preview

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-preview-books/', get_books_json_preview, name="get_books_json_preview")

]

mybooks/urls.py
from django.urls import path
from mybooks.views import mybooks, get_mybooks_json, book_return, promote_to_admin, get_mybooks_json_flutter, promote_to_admin_flutter, book_return_flutter

app_name = 'mybooks'

urlpatterns = [
    path('', mybooks, name='mybooks'),
    path('get-mybooks/', get_mybooks_json, name='get_mybooks_json'),
    path('get-mybooks-flutter/<str:username>', get_mybooks_json_flutter, name='get_mybooks_json_flutter'),
    path('book-return/<int:id>', book_return, name='book_return'),
    path('book-return-flutter/<int:id>', book_return_flutter, name='book_return_flutter'),
    path('promote-to-admin/<int:id>', promote_to_admin, name='promote_to_admin'),
    path('promote-to-admin-flutter/', promote_to_admin_flutter, name='promote_to_admin_flutter'),
]

tales_tails_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('mybooks/', include('mybooks.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

user_profile/urls.py
from django.urls import path
from user_profile.views import user_profile, get_user_json, edit_profile, show_user_json, edit_profile_flutter, edit_profile_flutter_user


app_name = 'user_profile'

urlpatterns = [
    path('', user_profile, name='user_profile'),
    path('get-user/', get_user_json, name='get_user_json'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('show-user/', show_user_json, name='show_user_json'),
    path('edit-profile-admin/', edit_profile_flutter, name='edit_profile'),
    path('edit-profile-user/', edit_profile_flutter_user, name='edit_profile_flutter_user'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block meta %}
        {% endblock meta %}
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Mochiy+Pop+P+One&family=Poppins:wght@400;500;600;700&display=swap');
            @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Darumadrop+One&family=EB+Garamond&family=Mochiy+Pop+P+One&display=swap');
          </style>
      <script src="https://cdn.tailwindcss.com"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

    </head>

    <body style="background-color: #F39B00;">
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
{% extends 'base.html' %}

{% block content %}

<link rel = "stylesheet"
href = "https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One">
<link rel = "stylesheet"
href = "https://fonts.googleapis.com/css2?family=Darumadrop+One">

<style>
    #card-navbar {
        font-family: 'Mochiy Pop P One';
        border-color: #724E2B;
        background: #FEFADD;
    }
</style>

<nav id = "card-navbar" class="relative flex w-full flex-wrap items-center justify-between bg-orange-100 py-2 lg:py-4 border-b-4 border-yellow-900">
    <div class="flex w-full flex-wrap items-center justify-between px-3">
        <div class="flex">
            <h1 class="ml-2 text-xl text-yellow-900"><a href="../">Tails & Tales</a></h1>
            <a href="{% url 'catalog:catalog' %}" class="text-yellow-900 pl-8 pt-1">Catalogue</a>
            {% if user.user_type == 'ADMIN' %}

            <a href="{% url 'mybooks:mybooks' %}" class="text-yellow-900 pl-8 pt-1">List of Users</a>
            <a href="{% url 'catalog:add_book' %}" class="text-yellow-900 pl-8 pt-1">Add new Book</a>

            {% else %}
            <a href="{% url 'mybooks:mybooks' %}" class="text-yellow-900 pl-8 pt-1">My Book</a>
            {% endif %}
        </div>
            <div class="flex">
                <!-- <div class="max-w-md pt-1">
                    <form action="" class="relative mx-auto w-max text-yellow-900">
                      <input type="search" placeholder="Find book" 
                            class="peer cursor-pointer relative z-10 h-8 w-8 rounded-full focus:border bg-transparent pl-12 outline-none focus:w-full focus:cursor-text focus:border-slate-300 focus:pl-16 focus:pr-4" />
                      <svg xmlns="http://www.w3.org/2000/svg" class="absolute inset-y-0 my-auto h-8 w-12 border-r border-transparent px-3.5 peer-focus:border-slate-300 peer-focus:stroke-white-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                      </svg>
                    </form>
                  </div>
                  <div> -->
                    <div class="relative inline-block text-left">
                        <div>
                          <button type="button" class="inline-flex w-full justify-center gap-x-1.5 text-yellow-900 px-3 py-2 font-semibold  hover:underline" id="showPopUp" aria-expanded="true" aria-haspopup="true">
                            {{ username }}
                            <svg class="-mr-1 h-6 w-6 text-yellow-900" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                              <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                            </svg>
                          </button>
                        </div>
                      
                        <div class="absolute hidden right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1" id="modal">
                          <div class="py-1" role="none">
                            <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                            {% if user.user_type == 'ADMIN' %}
                            <a href="{% url 'mybooks:mybooks' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">List of Borrower</a>
                            {% else %}
                            <a href="{% url 'mybooks:mybooks' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">My Book</a>
                            {% endif %}
                            <a href="{% url 'user_profile:user_profile' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">Edit Profile</a>
                            <a href="{% url 'main:logout' %}" type="submit" class="text-gray-700 block w-full px-4 py-2 text-left text-sm" role="menuitem" tabindex="-1" id="menu-item-2">Sign out</a>
                          </div>
                        </div>
                      </div>
                  </div>
            </div>
        </div>
        
    </div>
  </nav>

  <div id="add-book" class="rounded shadow-lg bg-amber-500 h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-opacity-50 hidden"></div>

  <script>
  $(document).ready(function() {
      $("#showPopUp").click(function() {
          $("#modal").toggleClass("hidden"); // Menggunakan toggleClass untuk mengganti class 'hidden'
      });
  });  
  </script>
{% endblock %}