catalog/urls.py
from django.urls import path
from catalog.views import catalog, search_books, get_books_json, search_book, book_borrowed, delete_book, add_book, book_borrowed_flutter, add_book_flutter, delete_book_flutter
from user_profile.views import get_user_json

app_name = 'catalog'

urlpatterns = [
    path('', catalog, name='catalog'),
    path("search/<str:query>", search_books, name='search'),
    path("get-books/", get_books_json, name='get_books_json'),
    path("search-book/", search_book, name='search_book'),
    path("borrow-book/<int:id>", book_borrowed, name='borrow_book'),
    path("delete-book/<int:id>", delete_book, name='delete_book'),
    path('get-user/', get_user_json, name='get_user_json'),
    path('add-book/', add_book, name='add_book'),
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
    path('book-borrowed-flutter/<int:id>', book_borrowed_flutter, name='borrow_book_flutter')
]

main/urls.py
from django.urls import path
from main.views import main, register, login_user, logout_user, get_books_json_preview

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-preview-books/', get_books_json_preview, name="get_books_json_preview")

]

mybooks/urls.py
from django.urls import path
from mybooks.views import mybooks, get_mybooks_json, book_return, promote_to_admin, get_mybooks_json_flutter, promote_to_admin_flutter, book_return_flutter

app_name = 'mybooks'

urlpatterns = [
    path('', mybooks, name='mybooks'),
    path('get-mybooks/', get_mybooks_json, name='get_mybooks_json'),
    path('get-mybooks-flutter/<str:username>', get_mybooks_json_flutter, name='get_mybooks_json_flutter'),
    path('book-return/<int:id>', book_return, name='book_return'),
    path('book-return-flutter/<int:id>', book_return_flutter, name='book_return_flutter'),
    path('promote-to-admin/<int:id>', promote_to_admin, name='promote_to_admin'),
    path('promote-to-admin-flutter/', promote_to_admin_flutter, name='promote_to_admin_flutter'),
]

tales_tails_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('mybooks/', include('mybooks.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

mybooks/models.py
from django.db import models

# Create your models here.

mybooks/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required, login_required
from main.models import User, Book
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from main.forms import RegisterUserForm
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
import json

@login_required(login_url='/login')
def mybooks(request):
    user = request.user
    if user.user_type == 'ADMIN':
        all_borrowed_books = Book.objects.filter(is_borrowed = True).values()
        all_member_user = User.objects.filter(user_type = 'MEMBER')
        users_book_count = User.objects.annotate(book_count=Count('book'))
        context = {
            'user': user,
            'member_users': all_member_user,
            'books': all_borrowed_books,
            'users_book_count': users_book_count,
        }
        return render(request, 'listpeminjam.html', context)
    else :
        books = Book.objects.filter(borrower=request.user)
        context ={
            'books': books
        }
        return render(request, "mybooks.html", context)
        

def get_mybooks_json(request):
    data = Book.objects.filter(borrower=request.user)
    return HttpResponse(serializers.serialize('json', data),
        content_type="application/json")

def get_mybooks_json_flutter(request, username):
    # Retrieve the user object based on the provided username
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        # Handle the case where the user doesn't exist
        return HttpResponse(status=404)

    # Filter books based on the obtained user object
    data = Book.objects.filter(borrower=user)

    # Serialize and return the data
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

def book_return(request, id):
    if request.method == 'GET':
        data = Book.objects.get(pk=id)
        data.is_borrowed = False
        data.borrower = None
        data.save()
        return HttpResponse(b"SUCCESS", status=201)
    return HttpResponseNotFound()

def book_return_flutter(request, id) :
    if request.method == 'GET':
        data = Book.objects.get(pk=id)
        data.is_borrowed = False
        data.borrower = None
        data.save()
        return JsonResponse({"status": "success"}, status=200)
    return JsonResponse({"status": "error"}, status=401)

def promote_to_admin(request, id):
    print('tes')
    user = User.objects.get(pk=id)
    user_books = Book.objects.filter(borrower=user)
    for book in user_books:
        book.is_borrowed = False
        book.borrower = None
        book.save()
    if (user.user_type == "MEMBER"):
        user.user_type = "ADMIN"
    else:
        user.user_type= "MEMBER"
    user.save()
    return redirect('mybooks:mybooks')

@csrf_exempt
def promote_to_admin_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        user = User.objects.get(email=data["email"])

        user_books = Book.objects.filter(borrower=user)
        for book in user_books:
            book.is_borrowed = False
            book.borrower = None
            book.save()
        if (user.user_type == "MEMBER"):
            user.user_type = "ADMIN"
        else:
            user.user_type= "MEMBER"

        user.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

mybooks/templates/listpeminjam.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<div>
    {% include 'navbar.html' %}

    <div class='max-w-6xl mx-auto mt-20 flex'>
        <div class="relative flex items-center w-full h-12 rounded-lg focus-within:shadow-lg bg-orange-100 overflow-hidden border-4 border-yellow-900">
            <div class="grid place-items-center h-full w-12 text-gray-300">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-900" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
            </div>
        <form method=GET id="searchForm" action="{% url 'catalog:search_book' %}" class="w-full">
            <input
            class="peer h-full w-full outline-none text-sm text-gray-700 px-2 bg-orange-100"
            type="text"
            id="search"
            name="searchTitle"
            placeholder="Search title..." /> 

        </form>
        </div>
        
        
    </div>

    <div>
        <div id="data_books" class="flex flex-wrap justify-center py-5 px-4 grow-0 w-100" >
            {% for member_user in member_users %}
            <div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center bg-orange-100 border-4 border-yellow-900">
        
                <div class=" px-20 pt-4">
                    <img width="150" height="200"  src="https://cdn.discordapp.com/attachments/967282111348367421/1168166620171083867/test.jpg?ex=6550c6f1&is=653e51f1&hm=b2d7d49aee1fd5a5fa3ca9e6df9b409d25f7b89788d94345b9b32a12fc5a1871&" alt="no image">
                </div>
                <div>
                    <div class= "data pr-1 pt-2 tag">
                        <h1 class="truncate">{{member_user.username}}</h1>
                    
                    </div>
                    <p class=" data pt-3 text-sm pb-2">Total buku dipinjam: <span class="ml-2">xx</span></p>
                
     
                    <div class="w-full pb-2">
                        <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" id="{{member_user.id}}" onclick="openModalUser(this.id)">
                            Details
                        </button>
                    </div>

                    <div class="w-full pb-2">
                        <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded">
                            <a href="{% url 'mybooks:promote_to_admin' member_user.id %}">Promote to Admin</a>
                        </button>
                    </div>
                </div>
            </div>  
            <div id="ModalUser{{member_user.id}}" class="modal fixed hidden inset-0 z-50 overflow-auto bg-black bg-opacity-50 flex items-center justify-center">
                <div class="modal-content bg-white p-4 rounded max-w-md mx-auto">
                    <!-- Modal Header -->
                    <div class="modal-header mb-4">
                        <span id="{{member_user.id}}" class="modal-close cursor-pointer text-2xl" onclick="closeModalUser(this.id)">&times;</span>
                        <h2 class="text-lg font-bold">Modal Title</h2>
                    </div>
                    <!-- Modal Body -->
                    <div class="modal-body">
                        <p>{{ member_user.first_name }} {{ member_user.last_name }}</p>
                        <p>{{ member_user.username }}</p>
                        <p>{{ member_user.date_of_birth }}</p>
                        <p>{{ member_user.email }}</p>
                        
                    </div>
                </div>
            </div>
            
            {% endfor %}  

        </div>

</div>

<!-- START Modal Edit Profile -->
  
<!-- END Modal Edit Profile -->

<script>
    document.getElementById('openModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.remove('hidden');
});

document.getElementById('closeModal').addEventListener('click', function() {
    document.getElementById('myModal').classList.add('hidden');
});


function openModalUser(Id) {
    document.getElementById('ModalUser' + Id).classList.remove('hidden');
    }

function closeModalUser(Id) {
    document.getElementById('ModalUser' + Id).classList.add('hidden');
    }

</script>

{% endblock %}

mybooks/templates/mybooks.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<style>
    .data{
        font-family: 'Mochiy Pop P One';
    } 
    .tag {
    display: inline-block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 18em;
    text-align: center;
}

</style>
<div>
    {% include 'navbar.html' %}

    <div class="flex justify-center">
        <h1 class="p-5 m-5 text-4xl border-4 rounded-xl" style="background-color: #DBBC7F; color: #FEFADD; -webkit-text-stroke: 2px #724E2B; font-family: 'Darumadrop One'; border-color: #724E2B;">List of Borrowed Books</h1>
    </div>
    
    <div class="flex justify-center m-5">
        <h2 id="countBorrow" class="text-xl" style="font-family: 'Mochiy Pop P One'; color: #724E2B;"></h2>
    </div>

    <div class='max-w-6xl mx-auto mt-20 flex'>
        <div class="relative flex items-center w-full h-12 rounded-lg focus-within:shadow-lg bg-orange-100 overflow-hidden border-4 border-yellow-900">
            <div class="grid place-items-center h-full w-12 text-gray-300">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-900" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
            </div>
        <form method=GET id="searchForm" action="{% url 'catalog:search_book' %}" class="w-full">
            <input
            class="peer h-full w-full outline-none text-sm text-gray-700 px-2 bg-orange-100"
            type="text"
            id="search"
            name="searchTitle"
            placeholder="Search title..." /> 

        </form>
        </div>
        
        <div class="relative inline-block">
            <div>
                <button id="showPopUpFilter" type="button">
                    <svg width="34" height="24" viewBox="0 0 49 39" fill="none" xmlns="http://www.w3.org/2000/svg" class="ml-2 mt-2">
                        <path d="M14.1594 4.24951H44.6378H14.1594Z" fill="white"/>
                        <path d="M14.1594 4.24951H44.6378" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M4 4.2748L4.0254 4.24658L4 4.2748Z" fill="white"/>
                        <path d="M4 4.2748L4.0254 4.24658" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M4 19.514L4.0254 19.4858L4 19.514Z" fill="white"/>
                        <path d="M4 19.514L4.0254 19.4858" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M4 34.7533L4.0254 34.7251L4 34.7533Z" fill="white"/>
                        <path d="M4 34.7533L4.0254 34.7251" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M14.1594 19.4888H44.6378H14.1594Z" fill="white"/>
                        <path d="M14.1594 19.4888H44.6378" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M14.1594 34.728H44.6378H14.1594Z" fill="white"/>
                        <path d="M14.1594 34.728H44.6378" stroke="#FEFADD" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>    
                </button>
            </div>

            <div class="absolute hidden right-0 z-10 mt-5 w-56 origin-top-right rounded-md bg-orange-100 border-4 border-yellow-900 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1" id="modalFilter">
                <div class="py-1" role="none">
                  <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                  <p class=" ml-2 text-yellow-900">Search filtered by (only can choose one)</p>
                  <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                  
                    <div class="inline-flex items-center">
                        <label
                        class="relative flex items-center p-3 rounded-full cursor-pointer"
                        for="author">
                        <input
                            id="author"
                            type="checkbox"
                            class="before:content[''] peer relative h-5 w-5 cursor-pointer appearance-none rounded-md border-4 border-yellow-900 transition-all before:absolute before:top-2/4 before:left-2/4 before:block before:h-12 before:w-12 before:-translate-y-2/4 before:-translate-x-2/4 before:rounded-full before:border-yellow-900 before:opacity-0 before:transition-opacity checked:border-pink-500 checked:bg-pink-500 checked:before:bg-pink-500 hover:before:opacity-10"
                        />
                        <div class="absolute text-white transition-opacity opacity-0 pointer-events-none top-2/4 left-2/4 -translate-y-2/4 -translate-x-2/4 peer-checked:opacity-100">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-3.5 w-3.5"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            stroke="currentColor"
                            stroke-width="1"
                            >
                            <path
                                fill-rule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clip-rule="evenodd"
                            ></path>
                            </svg>
                        </div>
                        </label>
                        <label
                        class="mr-5 text-yellow-900 cursor-pointer select-none"
                        for="author"
                        >
                        Author
                        </label> 
                    </div>      
                    <div class="inline-flex items-center">
                        <label
                        class="relative flex items-center p-3 rounded-full cursor-pointer"
                        for="category">
                        <input
                            id="category"
                            type="checkbox"
                            class="before:content[''] peer relative h-5 w-5 cursor-pointer appearance-none rounded-md border-4 border-yellow-900 transition-all before:absolute before:top-2/4 before:left-2/4 before:block before:h-12 before:w-12 before:-translate-y-2/4 before:-translate-x-2/4 before:rounded-full before:border-yellow-900 before:opacity-0 before:transition-opacity checked:border-pink-500 checked:bg-pink-500 checked:before:bg-pink-500 hover:before:opacity-10"
                        />
                        <div class="absolute text-white transition-opacity opacity-0 pointer-events-none top-2/4 left-2/4 -translate-y-2/4 -translate-x-2/4 peer-checked:opacity-100">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-3.5 w-3.5"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            stroke="currentColor"
                            stroke-width="1"
                            >
                            <path
                                fill-rule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clip-rule="evenodd"
                            ></path>
                            </svg>
                        </div>
                        </label>
                        <label
                        class="mr-5 text-yellow-900 cursor-pointer select-none"
                        for="category"
                        >
                        Category
                        </label> 
                    </div>   
                </div>
              </div>
            </div>
        </div>
        
    </div>

    <div>{% if search %}
        <div id="data_book" class="flex flex-wrap justify-center py-5 px-4 grow-0 w-100">
            {% for book in books %}
            <div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center bg-orange-100 border-4 border-yellow-900">
        
                <div class=" px-20 pt-4">
                    <img src="{{book.image_link}}" alt="no image">
                </div>
                <div>
                    <div class= "data pr-1 pt-2 tag">
                        <h1 class="truncate">{{book.title}}</h1>
                    
                    </div>
                    <p class=" data pt-3 text-sm pb-2">Stock: <span class="ml-2">1</span></p>
                
                    <div class="w-full pb-2">
                        <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded ">
                            Details
                        </button>
                    </div>
                
                    <div class="w-full pb-2">
                        <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded">
                            Review
                        </button>
                    </div>
                </div>
        
        
            </div>      
            {% endfor %}
            
        </div>
        {% else %}
        <div id="data_books" class="flex flex-wrap justify-center py-5 px-4 grow-0 w-100" >
        
        </div>
        {% endif %}  
    </div>

</div>

<script>
    const checkboxes = document.querySelectorAll('input[type="checkbox"]');

// Menambahkan event listener untuk setiap checkbox
checkboxes.forEach(checkbox => {
    checkbox.addEventListener('change', function() {
        if (this.checked) {
            // Membatalkan pilihan pada checkbox lain
            checkboxes.forEach(otherCheckbox => {
                if (otherCheckbox !== this) {
                    otherCheckbox.checked = false;
                }
            });
        }
    });
});

$(document).ready(function() {
            $("#showPopUpFilter").click(function() {
                $("#modalFilter").toggleClass("hidden"); // Menggunakan toggleClass untuk mengganti class 'hidden'
            });
            $("#author, #category").on('change',function(){
                let author = $("#author").is(":checked");
                let category = $("#category").is(":checked");

                if(author){
                    $("#search").attr("placeholder", "Search author...");
                    $("#search").attr("name", "searchAuthor")
                } else if(category){
                    $("#search").attr("placeholder", "Search category...");
                    $("#search").attr("name", "searchCategory")
                } else {
                    $("#search").attr("placeholder", "Search title...");
                    $("#search").attr("name", "searchTitle")
                }
            });
            $("#search").keypress(function(e){
                if(e.which === 13){
                    event.preventDefault();
                    $("#searchForm").submit();
         
                }
            });
        });
    


async function getProducts() {
    return fetch("{% url 'mybooks:get_mybooks_json' %}").then((res) => res.json())
}

async function refreshProducts(){
    const product = await getProducts()
    document.getElementById("data_books").innerHTML = ""
    document.getElementById("countBorrow").innerHTML = ""
    let htmlString = ""
    let htmlStringCount = `You borrowed <span style="color: #C85A35;">${ product.length } books</span> from this site`
    product.forEach((item) => {
        htmlString += `<div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center bg-orange-100 border-4 border-yellow-900">
        
        <div class=" px-20 pt-4">
            <img src="${item.fields.image_link}" alt="no image">
        </div>
        <div>
            <div class= "data pr-1 pt-2 tag">
                <h1 class="truncate">${item.fields.title}</h1>
            
            </div>
        
            <div class="w-full pb-2">
                <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded ">
                    Details
                </button>
            </div>
        
            <div class="w-full pb-2">
                <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" onclick="returnBook(${item.pk})">
                    Return
                </button>
            </div>
        </div>


    </div>      
`
    })
    document.getElementById("data_books").innerHTML = htmlString
    document.getElementById("countBorrow").innerHTML = htmlStringCount
}

refreshProducts()

function returnBook(id){
    fetch(`book-return/${id}`, {
        method: "GET",
    }).then(refreshProducts)
    
}

</script>

{% endblock %}