catalog/urls.py
from django.urls import path
from catalog.views import catalog, search_books, get_books_json, search_book, book_borrowed, delete_book, add_book, book_borrowed_flutter, add_book_flutter, delete_book_flutter
from user_profile.views import get_user_json

app_name = 'catalog'

urlpatterns = [
    path('', catalog, name='catalog'),
    path("search/<str:query>", search_books, name='search'),
    path("get-books/", get_books_json, name='get_books_json'),
    path("search-book/", search_book, name='search_book'),
    path("borrow-book/<int:id>", book_borrowed, name='borrow_book'),
    path("delete-book/<int:id>", delete_book, name='delete_book'),
    path('get-user/', get_user_json, name='get_user_json'),
    path('add-book/', add_book, name='add_book'),
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
    path('book-borrowed-flutter/<int:id>', book_borrowed_flutter, name='borrow_book_flutter')
]

main/urls.py
from django.urls import path
from main.views import main, register, login_user, logout_user, get_books_json_preview

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-preview-books/', get_books_json_preview, name="get_books_json_preview")

]

tales_tails_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('mybooks/', include('mybooks.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from catalog.models import Book

class User(AbstractUser):
    ROLES = [('MEMBER', 'Member'),
             ('ADMIN', 'Admin')]
    user_type = models.CharField(max_length=20, choices=ROLES, default='MEMBER')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    fav_color = models.CharField(max_length=255)

class Member(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    borrowed_books = models.ManyToManyField(Book, blank=True)
    
    class Meta:
        permissions = [
            ("can_view_member_profile", "Can view member profile"),
            ("can_borrow_books", "Can borrow books"),
        ]

class Admin(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        permissions = [
            ("can_view_admin_profile", "Can view admin profile"),
            ("can_view_member_list", "Can view member list"),
        ]

class BookReview(models.Model):
    book = models.ForeignKey(Book, related_name = 'reviews', on_delete = models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, related_name = 'reviews', on_delete = models.CASCADE, null=True, blank=True)

    content = models.TextField(blank = True, null = True)
    stars = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add = True)

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from main.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 125px;'})
    )
    last_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 125px;'})
    )
    username = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 255px;'})
    )
    email = forms.EmailField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 255px;'})
    )
    date_of_birth = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 255px;'})
    )
    fav_color = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'style': 'width: 255px;'})
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'style': 'width: 255px;'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'style': 'width: 255px;'}))

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "date_of_birth", "fav_color"]

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required, login_required
from main.models import User, Book
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from main.forms import RegisterUserForm

from django.contrib.auth import authenticate, login, logout


"""
CTT. (hapus kalo udah selesai, update sesuai kebutuhan)
1. jika ingin hanya beberapa tipe user yang menjalankan fungsi tertentu, gunakan @permission_required diatas fungsi tersebut
eg.

@permission_required('main.permissionPadaModels')
def ....

permissionPadaModels bisa diatur di models.py member/admin sesuai kebutuhan pada:
eg.
permissions = [
            ("permissionPadaModels, "contoh aja"),
        ]

2. bisa juga pengecekan jenis user dengan user.user_type untuk tau role user ADMIN/MEMBER, ctt."user" tergantung var yang digunakan untuk nyimpan.
"""

@login_required(login_url='/login')

def main(request):
    return render(request, "main.html")

def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data["username"],
                email=form.cleaned_data["email"],
                first_name=form.cleaned_data["first_name"],
                last_name=form.cleaned_data["last_name"],
                date_of_birth=form.cleaned_data["date_of_birth"],
                fav_color=form.cleaned_data["fav_color"],
            )

            user.set_password(form.cleaned_data["password1"])
            user.save()
            login(request, user)
            return redirect('main:login')           
    else:
        form = RegisterUserForm()

    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    error_message = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:main')
        else:
            error_message = 'Sorry, incorrect username or password. Please try again.'
    context = {'error_message': error_message}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('main:login')


def get_books_json_preview(request):
    data = Book.objects.all()[:2]  # Mengambil hanya 4 data pertama
    return HttpResponse(serializers.serialize('json', data),
        content_type="application/json")

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel = "stylesheet"
    href = "https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One">
    <link rel = "stylesheet"
    href = "https://fonts.googleapis.com/css2?family=Darumadrop+One">

    <style>
        body {
            font-family: 'Mochiy Pop P One';
        }

        .circle {
            width: 15px;
            height: 15px;
            background-color: #BC905F;
            border-radius: 50%;
            position: absolute;
            border: 2px solid #724E2B;
        }

        .top-left {
            top: 15px;
            left: 15px;
        }

        .top-right {
            top: 15px;
            right: 15px;
        }

        .bottom-left {
            bottom: 15px;
            left: 15px;
        }

        .bottom-right {
            bottom: 15px;
            right: 15px;
        }
    
        h1 {
            color: #2A2136;
            font-family: Darumadrop One;
            font-size: 76px;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
        }

        p {
            text-align: center;
            color: #2A2136;
        }

        #card {
            margin-top: 100px;
            border-radius: 20px;
            border: 6px solid #724E2B;
            background: #FEFADD;
            transform: scale(1.2);
            transform-origin: center;
        }

        #login-text {
            font-size: 48px;
            margin-bottom: 20px;
        }

        #username-label, #password-label {
            color: #2A2136;
            font-size: 1.2em; 
        }

        #username, #password {
            border-radius: 10px;
            border: 4px solid #724E2B;
            background: #DBBC7F;
            color: #724E2B;
            font-size: 1.1em; 
        }

        #button {
            border-radius: 10px;
            border: 4px solid #724E2B;
            color: #724E2B;
            background: #FEFADD;
            transform: scale(1.2); 
            transform-origin: center;
            text-align: center; 
            padding-left:10px; 
            padding-right: 10px;
            padding-top: 5px;
            padding-bottom: 5px;
        }

        #button:hover {
            color: #FEFADD;
            background: #724E2B;
        }

        #register-now:hover {
            text-decoration: underline;
            text-decoration-thickness: 2px;
        }

        .account-text {
            margin: 5px 0;
        }
    </style>
    

    <body>
        {% include 'navbar.html' %}

    <div id = "card" class="w-full max-w-md mx-auto mt-10 p-6 bg-orange-100 border border-yellow-900  border-4 rounded-lg">
        <div class="circle top-left"></div>
        <div class="circle top-right"></div>
        <div class="circle bottom-left"></div>
        <div class="circle bottom-right"></div>

        <form method="POST" action="">
            {% csrf_token %}
            <div class="space-y-4" style = "text-align: center;">
                <div class="flex flex-col">
                    <h1 class="text-center text-2xl mb-4" id = "login-text">Login</h1>
                </div>

                <div class="flex flex-col">
                    <label id = "username-label" for="username" class="text-gray-700">Username</label>
                    <input class = "border border-yellow-900 rounded-lg" type="text" name="username" id="username" placeholder="" class="form-input" style = "text-align: center;" >
                </div>

                <div class="flex flex-col">
                    <label id = "password-label" for="password" class="text-gray-700">Password</label>
                    <input class = "border border-yellow-900 rounded-lg" type="password" name="password" id="password" placeholder="" class="form-input" style = "text-align: center;">
                </div>

                <p class="mt-2" style="color: #2A2136; margin-bottom: 20px;" class="account-text">Don't have an account yet? <br> <a id = "register-now" href="{% url 'main:register' %}" style="color: #C85A35;" class="account-text">Register Now</a> </p>

                <div class="flex justify-center">
                    <button id = "button" type="submit">Login</button>
                </div>

                <div class="text-center mt-2" style="color: red;">
                    {% if error_message %}
                        {{ error_message }}
                    {% endif %}
                </div>
            </div>
        </form>

        {% if messages %}
            <ul class="mt-4">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    </div>
</body>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<style>
     .data{
        font-family: 'Mochiy Pop P One';
    } 
</style>

{% include 'navbar.html' %}

<div class="">
    <div class="flex flex-col justify-center text-center pt-5">
        <div class="flex justify-center w-100 h-50 pt-10">
            <h1 class="px-60 py-2 text-6xl border-4 rounded-xl" style="background-color: #DBBC7F; color: #FEFADD; -webkit-text-stroke: 2px #724E2B; font-family: 'Darumadrop One'; border-color: #724E2B;">About us</h1>
        </div>
        <p class="data text-center text-4xl px-80 pt-10 leading-10" style="color: #724E2B;">
            Tales and Tails Cafe adalah sebuah Cafe yang mengambil 
            konsep Cat Cafe, tetapi memiliki sebuah perpustakaan untuk meminjam buku juga. 
            Cafe ini memiliki tujuan untuk memadukan suasana santai kafe dengan kemudahan akses ke 
            koleksi buku yang beragam, hal ini bertujuan untuk menciptakan ruang yang menggabungkan dua 
            kegiatan yang menyenangkan dan mendidik.
        </p>
        <div class="pt-20 py-60" style="display: flex; justify-content: center; align-items: center;">
            <div class="flex border-4 rounded-xl justify-center pt-10" style="background-color: #FEFADD; font-family: 'Darumadrop One'; border-color: #724E2B; width: 800px; height: 700px;">
                <div class="flex flex-col">
                    <h1 class="data py-2 text-6xl text-slate-900">DISCOVER BOOKS</h1>
                    <h2 class="data py-2 text-2xl text-amber-700">Just one click away!</h2>
                    <div id="data_books" class="flex flex-wrap justify-center py-5 px-4 grow-0 w-100" >

                    </div>
                    <div class="rounded shadow-lg bg-amber-500 h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-opacity-50 hidden" id="detail-buku">
   
                    </div>
                    <button class="bg-orange-700 border-4 border-yellow-900 rounded-md ">
                        <a href="{% url 'catalog:catalog' %}" class="text-2xl text-white pt-1 pb-1 block w-full h-full">See More</a>
                    </button>
                </div>
               

            </div>
                
        </div>  
    </div>
    
   
</div>

<script>
async function getProducts() {
    return fetch("{% url 'main:get_books_json_preview' %}").then((res) => res.json())
}

async function refreshProducts(){
    const product = await getProducts()
    document.getElementById("data_books").innerHTML = ""
    let htmlString = ""
    product.forEach((item) => {
        if (item.fields.is_borrowed) {
            htmlString += `<div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center border-4 border-yellow-900" style="background-color: #FEFADD;">
            
            <div class=" px-20 pt-4">
                <img src="${item.fields.image_link}" alt="no image">
            </div>
            <div>
                <div class= "data pr-1 pt-2 tag">
                    <h1 class="truncate">${item.fields.title}</h1>
                
                </div>
                <p class=" data pt-3 text-sm pb-2 text-rose-600">Not Available</p>
            
                <div class="w-full pb-2">
                <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" onclick="detailsProduct('${item.fields.image_link}',
                    '${item.fields.title.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.description.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.author.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.date_published.replace(/'/g, "\\'").replace(/"/g, '&quot;')}',
                    '${item.fields.rating.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.category.replace(/'/g, "\\'").replace(/"/g, '&quot;')}',
                    '${item.pk}', '${item.fields.is_borrowed}')">
                    Details
                </button>
            </div>
            
                <div class="w-full pb-2">
                    <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded">
                        Review
                    </button>
                </div>
            </div>
        </div>      
        `
        } else {
            htmlString += `<div class="relative px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center border-4 border-yellow-900 style="background-color: #FEFADD;"">
            
            <div class=" px-20 pt-4">
                <img src="${item.fields.image_link}" alt="no image">
            </div>
            <div>
                <div class= "data pr-1 pt-2 tag">
                    <h1 class="truncate">${item.fields.title}</h1>
                
                </div>
                <p class=" data pt-3 text-sm pb-2 text-emerald-500">Available</p>
            
                <div class="w-full pb-2">
                <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" onclick="detailsProduct('${item.fields.image_link}',
                    '${item.fields.title.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.description.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.author.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.date_published.replace(/'/g, "\\'").replace(/"/g, '&quot;')}',
                    '${item.fields.rating.replace(/'/g, "\\'").replace(/"/g, '&quot;')}', 
                    '${item.fields.category.replace(/'/g, "\\'").replace(/"/g, '&quot;')}',
                    '${item.pk}', '${item.fields.is_borrowed}')">
                    Details
                </button>
            </div>
            
                <div class="w-full pb-2">
                    <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded">
                        Review
                    </button>
                </div>
            </div>
        </div>      
        `
        }
    })
    document.getElementById("data_books").innerHTML = htmlString
}

async function detailsProduct(image_link, title, desc, author, publish_date, rating, category, id, is_borrowed) {
        document.getElementById('detail-buku').innerHTML = ""
        htmlString = ` 
        <div class="px-2 flex flex-col rounded-lg shadow-md w-100 m-6 overflow-hidden text-center bg-orange-100 border-4 border-yellow-900">
            <h3 class="data text-2xl pb-4 pt-3">Book Details</h3>
            <div class="text-center">
                <div class="px-20 pt-4 inline-block">
                    <img src="${image_link}" alt="no image">
                </div>
            </div>
            <div class="flex flex-row pb-6">
                <div class="text-center">
                    <div class="pb-5">
                        <h2 class="data text-lg">${title}</h2>
                    </div>
                <div class="pb-5 text-left">
                    <h3 class="dec font-medium text-sm px-2"><t/>${desc}</h3>
                </div>
                <div class="text-center">
                    <p class = "dec font-bold text-left mb-2 ml-2 text-sm"> Detail </p>
                    <table class="dec font-semibold text-sm text-justify ml-2">
                        <tr>
                            <td>
                                <h3>Author:</h3>
                            </td>
                            <td>
                                <h3 class="ml-2">${author}</h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3 >Published Date:</h3>
                            </td>
                            <td>
                                <h3 class="ml-2">${publish_date}</h3>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <h3>Category:</h3>
                            </td>
                            <td>
                                <h3 class="ml-2">${category}</h3>
                            </td>
                        </tr>
                        
                    </table>
                </div>

            </div>
            </div>
            <div class="flex flex-row justify-center w-full pb-4">
                <div class="mr-3">
                    <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" onclick="backButton()">
                        Back
                    </button>
                </div>
                <div class="ml-3">
                    <button class="data text-yellow-900 w-40 border-4 border-yellow-900 rounded" id="borrowButton" onclick="borrowBook(${id})">
                        Borrow Book
                    </button>
                </div>
            </div>
            `
            document.getElementById('detail-buku').innerHTML = htmlString

            if(is_borrowed == 'true') {
                const borrowButton = document.getElementById('borrowButton');
                borrowButton.innerHTML = 'Not Available';
                borrowButton.setAttribute('onclick', 'handleBorrowFail()');
            }
        
        const popUp = document.getElementById('detail-buku')
        popUp.classList.remove('hidden')
    }

    async function backButton(){
        const popUp = document.getElementById('detail-buku')
        popUp.classList.add('hidden')
    }

    async function handleBorrowFail(){
        alert("This book is currently not available or you need to login first")
    }

    function borrowBook(id){
        const url = `catalog/borrow-book/${id}`
        const popUp = document.getElementById('detail-buku')
        fetch(url, {
            method: "GET",
        }).then(refreshProducts);
        popUp.classList.add('hidden')
        return false;
    }



refreshProducts()
</script>

{% endblock %}

main/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %} 
<title>Register</title>

<link href="https://fonts.googleapis.com/css2?family=Darumadrop+One&family=Mochiy+Pop+P+One&display=swap" rel="stylesheet">

<style>
    .circle {
        width: 15px;
        height: 15px;
        background-color: #BC905F;
        border-radius: 50%;
        position: absolute;
        border: 2px solid #724E2B;
    }

    .top-left {
        top: 15px;
        left: 15px;
    }

    .top-right {
        top: 15px;
        right: 15px;
    }

    .bottom-left {
        bottom: 15px;
        left: 15px;
    }

    .bottom-right {
        bottom: 15px;
        right: 15px;
    }

    #card {
            margin: 100px;
            border-radius: 20px;
            border: 6px solid #724E2B;
            background: #FEFADD;
            transform: scale(1.2);
            transform-origin: center;
        }

    #card-content {
        /* transform: scale(1.2); */
        transform-origin: center;
    }

    .form-group {
        margin: 10px 0;
    }
    
    .circle {
        width: 15px;
        height: 15px;
        background-color: #BC905F;
        border-radius: 50%;
        position: absolute;
        border: 2px solid #724E2B;
    }

    .top-left {
            top: 15px;
            left: 15px;
        }

        .top-right {
            top: 15px;
            right: 15px;
        }

        .bottom-left {
            bottom: 15px;
            left: 15px;
        }

        .bottom-right {
            bottom: 15px;
            right: 15px;
        }

    .form-label {
        display: block;
        font-family: 'Mochiy Pop P One', sans-serif;
        font-size: 12px;
        color: #2A2136;
    }

    .form-group input {
        background-color: #DBBC7F;
        color: #724E2B;
        border: 2px solid #724E2B;
        border-radius: 5px;
        font-family: 'Mochiy Pop P One', sans-serif;
        font-size: 12px;
        padding: 2px 4px;
    }

    .custom-button {
        background-color: #FEFADD;
        color: #724E2B;
        border: 2px solid #724E2B;
        border-radius: 5px;
        font-family: 'Mochiy Pop P One', sans-serif; 
        font-size: 13px;
        padding: 6px 12px;
        cursor: pointer;
        text-align: center; 
    }
    .custom-button:hover {
        background-color: #724E2B;
        color: #FEFADD;
    }

    #login-text:hover {
        text-decoration: underline;
        text-decoration-thickness: 2px;
        text-decoration-color: #C85A35;
    }

</style>

<body>
{% include 'navbar.html' %}

    <div class="flex justify-center items-center h-screen">
        <div class="p-4 rounded-lg shadow-md card" style="width: 650px; background-color: #FEFADD; color: #2A2136; border: 8px solid #724E2B; position: relative; border-radius: 20px;">
            <div class="circle top-left"></div>
            <div class="circle top-right"></div>
            <div class="circle bottom-left"></div>
            <div class="circle bottom-right"></div>
            
            <h1 class="text-3xl mb-1 text-center" style="font-family: 'Darumadrop One', sans-serif; font-size: 48px">SIGN UP</h1>
            <p class="text-center mb-4" style="font-family: 'Mochiy Pop P One', sans-serif; font-size: 12px;">
                Already a member? <a href="/login" style="color: #2A2136;"> <span style="color: #C85A35;">Login</span></a>
            </p>
            <div class="container" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
                <form method="POST">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td class="form-group">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                            </td>
                            <td class="form-group">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                            </td>
                        </tr>
                        <tr>
                            <td class="form-group">
                                {{ form.first_name }}
                            </td>
                            <td class="form-group">
                                {{ form.last_name }}
                            </td>
                        </tr>
                    </table>

                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                        {{ form.username }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                        {{ form.email }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.date_of_birth.id_for_label }}" class="form-label">Date of Birth (YYYY-MM-DD)</label>
                        {{ form.date_of_birth }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.fav_color.id_for_label }}" class="form-label">What’s Your Favorite Color?</label>
                        {{ form.fav_color }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.password1.id_for_label }}" class="form-label">Password</label>
                        {{ form.password1 }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.password2.id_for_label }}" class="form-label">Confirm Password</label>
                        {{ form.password2 }}
                    </div>
                    <div class="text-center">
                        <input type="submit" name="submit" value="Register" class="custom-button" />
                    </div>

                </form>
                <div class="text-center mt-2" style="font-family: 'Mochiy Pop P One', sans-serif; font-size: 12px; color: red;">
                    {% if form.errors %}
                        <div class="error">
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock content %}